services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- nvm install --lts
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python3 -m unittest
- docker build -t descalon/devops .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 descalon/devops:latest
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag descalon/devops descalon/devops
- docker push descalon/devops
env:
  global:
  - secure: SpmB51RdUgxTCRQNnppQUCApElzfpfosMeoC95KgXMrqlolVCr9xRBuxtnM7rvnG7GIj/hYR7xSzGoV63HgrRHg0TASLYvmgzJrksusbYhlhx0/hkUmXZgGvNLJPX/u7uQSGyvfqiggPmyohQcUlrFD99WJ9p1SaE7s35dniCI9WBmRJQ193E6kK0GOI6sPV/JuwEgN48uNsxTrbJ5KPpm0oOlPfK8eODY2faVzmxP0zWPpadpC4eZuQyjKQgZNkKesW5K1ICEof64y8a5K8RmQSSSHvgvF8ZSOtcn9Cqr8DqU1qDGhRJ0d3p5v5eudg/ervC5c2GgHyt2e8tNYL3Rm8DJy2lgnDFWTx+jky3kiflRZliP9rQEevDIuwu0kBNax7vChzIqW2Ha7u/cHFoNyiWTOpycAyprIpPN3eeGKwHJONhivESjiigyHN+4cFEE/QPBb4/Ij2YokmiGoAB7+vQ74xkX/T0mws/+re3TcWRCr4RHpTkTY2IWLcooHjXIOBmwJDSTkF+wqA0G3dupFAtT62pFN4Wl1BKOCB9cMJqHw67RdxUvKduGz6GHaWSYkFPkZVU0jpXKJiQUlK7wUKkuU5X3m+XIfuhK3aLgQ0x0tORO3xcKfDx8c9kVMFZ1qLCr/9NUxm5A4eWS4dAhYIsF520EOoXbjOSSGBk/Y=
  - secure: WfHVON3aqq9bVw/8/7g4zCBcPtw+Wo9lhQNrWJVE3FkcDxEpxDZMkHtVz4r8lZsUT2RcnRPG1PMCZJOakZVdyx6pBmmIvfAy5uoS+7aherg3Oct1O7mtwHHHVGHmNOVPtQ9XDPyiLTku3Zzel7HcZ/8HahnZjgR5/Emma+NrUKxPRzt8N8EFE1QkGgvCOVwblHHTCe3jDW1lwogZiOnQoXTa234WAGZV36cGcMq6xhilSU3m3VGWuIAIsRrkz2h809C3gUpsfjJtd1J5uJqYXQqionvWgOB737cfWU6lj8GG5vAcdlzvBhKYHBVFzHsjH2mu2EnaBYbeI1PvoBaFeoRXcCwbnZYMzXedBj0tXFbrVvyuCv8vKqa53VAdGKWb3eMbf0mgvgM4TrpjQ22WDSoOKEB8ORirtb0h+Iuhw16FIqXUT8kbSTysGRJ7mxyK4a1bJsRO92EsFgNk56RNph3YXKOBbei6r+Mh6+CkH6FNJ1zI+OjkwcBMeoVrcm0yfFozLdSP/BrJ3XzAqdy+CqHp+AZYMwXUHZfprhu2o0vumdquEWmaZESTvoOGxUWkQInUNvjTj/MMBJSS1sQ80CHfihuHYAIGtV+69MNdzcWuoz4tL+U5TtcqdKPw0IYGgnMIekJqITZXFa+5zp+ANeaKqhHRQFs1MOfNzxW/88w=
